clip:
  clip_architecture: ViT-B/16
  tau: 4
dataset:
  im_size:
  - 32
  - 32
  in_channels: 1
  input_dim:
  - 1
  - 1
  - 32
  - 32
  name: MNIST
  num_classes: 10
  root: ./_MNIST
diagnostics:
  diagnostics:
    Checkpoint: {}
    Progress: {}
    Timing: {}
    TrainAcc: {}
    TrainLoss: {}
    ValAcc: {}
    ValLoss: {}
  logging_defaults:
    log_interval: logarithmic
    save_freq: 4
    save_init: 5
method: RhoLoss
method_opt:
  balance: false
  ratio: 0.1
  ratio_scheduler: constant
  warmup_epochs: 0
networks:
  params:
    m_type: lenet
  type: LeNet
run_name: run_MNIST_RhoLoss_SGD_lr-0.01_CrossEntropy
run_name_format:
- run
- $dataset.name
- $method
- $training_opt.optimizer
- lr:
  - $training_opt.optim_params.lr
- $training_opt.loss_type
save_dir: ./experiments/20260626_132557_3_run_MNIST_RhoLoss_SGD_lr-0.01_CrossEntropy
seed: 10
teacher_model_source: clip
training_opt:
  batch_size: 320
  loss_params: {}
  loss_type: CrossEntropy
  num_data_workers: 4
  num_epochs: 100
  optim_params:
    lr: 0.01
    weight_decay: 0.0
  optimizer: SGD
  scheduler: constant
  scheduler_params: {}
  test_batch_size: 512
wandb:
  mode: offline
  project: Basic Baselines
